import type {ApeironCodeConfig} from '../../src/config/config.js';

export const createMockConfig = (overrides?: Partial<ApeironCodeConfig>): ApeironCodeConfig => ({
  defaultModel: 'mock-coder',
  defaultProvider: 'mock',
  models: {},
  baseUrls: {},
  apiKeyEnvNames: {},
  approvalMode: 'bypass',
  telemetry: false,
  theme: 'auto',
  localOnly: false,
  maxContextFiles: 10,
  maxFixAttempts: 3,
  maxFileSize: 200_000,
  maxIterations: 40,
  lsp: {
    enabled: true,
    fallbackOnFailure: true,
    idleTimeoutMs: 300_000,
    longLivedSessions: true,
    maxSessions: 5,
    requestTimeoutMs: 3_000,
  },
  memory: {autoSave: false, autoSuggest: true},
  tokenEfficiency: {
    context: {maxFullFiles: 4, maxSummaryFiles: 8},
    enabled: true,
    memory: {maxMemoryTokens: 800},
    reasoningStyle: {default: 'balanced'},
    tools: {dynamicExposureEnabled: true, maxToolOutputTokens: 1_200},
  },
  mcp: {servers: {}},
  sandbox: {fallbackPolicy: 'safe-readonly'},
  plugins: {directories: [], disabled: []},
  permissions: [],
  planning: {
    autoPlanForLargeTasks: true,
    largeTaskThreshold: 3,
    requireApproval: true,
    requireBeforeEdit: false,
  },
  web: {
    allowPrivateHosts: false,
    enabled: true,
    maxFetchChars: 6_000,
    maxSearchResults: 5,
    searchProvider: 'duckduckgo',
    userAgent: 'ApeironCode-Agent/0.1',
  },
  ignoredPaths: [],
  ...overrides,
});
