import {describe, expect, it} from 'vitest';

import {
  formatSchemaValidationFeedback,
  formatWriteFileInputError,
  isMissingWriteFileInput,
  normalizeToolInput,
  repairToolInputJson,
  shouldRetryToolInput,
  WRITE_FILE_REQUIRED_INPUT_ERROR,
} from '../../src/agent/toolInputRepair.js';

describe('repairToolInputJson', () => {
  it('returns valid JSON unchanged', () => {
    const r = repairToolInputJson('{"a":1}');
    expect(r.repaired).toBe(false);
    expect(r.unrecoverable).toBe(false);
    expect(r.json).toBe('{"a":1}');
  });

  it('normalizes empty / whitespace / null-ish input to {} (project_tree no-args)', () => {
    for (const raw of ['', '   ', '\n', 'null', 'undefined', '""']) {
      const r = repairToolInputJson(raw);
      expect(r.unrecoverable).toBe(false);
      expect(r.repaired).toBe(true);
      expect(JSON.parse(r.json)).toEqual({});
    }
  });

  it('repairs trailing commas', () => {
    const r = repairToolInputJson('{"a":1,}');
    expect(r.repaired).toBe(true);
    expect(JSON.parse(r.json)).toEqual({a: 1});
    expect(r.warnings.some((w) => w.includes('trailing'))).toBe(true);
  });

  it('unwraps double-stringified JSON', () => {
    const original = JSON.stringify({path: 'a.ts'});
    const doubled = JSON.stringify(original);
    const r = repairToolInputJson(doubled);
    expect(r.repaired).toBe(true);
    expect(JSON.parse(r.json)).toEqual({path: 'a.ts'});
    expect(r.warnings.some((w) => w.includes('double-stringified'))).toBe(true);
  });

  it('unwraps wrapped payloads with input field', () => {
    const wrapped = JSON.stringify({toolName: 'read_file', input: {path: 'a.ts'}}).replace(/\}$/u, ',}');
    const r = repairToolInputJson(wrapped);
    expect(r.repaired).toBe(true);
    expect(JSON.parse(r.json)).toEqual({path: 'a.ts'});
  });

  it('returns unrecoverable for hopelessly broken JSON', () => {
    const r = repairToolInputJson('not even close to json {{{');
    expect(r.unrecoverable).toBe(true);
  });
});

describe('normalizeToolInput', () => {
  it('returns input unchanged when already an object', () => {
    const r = normalizeToolInput('read_file', {path: 'x'});
    expect(r.valid).toBe(true);
    expect(r.input).toEqual({path: 'x'});
  });

  it('parses string input', () => {
    const r = normalizeToolInput('read_file', '{"path":"a.ts"}');
    expect(r.valid).toBe(true);
    expect(r.input).toEqual({path: 'a.ts'});
  });

  it('reports invalid for unrecoverable input', () => {
    const r = normalizeToolInput('read_file', 'not json {{{');
    expect(r.valid).toBe(false);
    expect(r.schemaErrors).toBeDefined();
  });
});

describe('formatSchemaValidationFeedback', () => {
  it('formats feedback with errors and no secret leakage', () => {
    const fakeBearer = `Bearer ${'a'.repeat(20)}`;
    const errors = ['path is required'];
    const out = formatSchemaValidationFeedback('read_file', errors);
    expect(out).toContain('read_file');
    expect(out).toContain('path is required');
    // No actual bearer token text is generated by the formatter
    expect(out).not.toContain(fakeBearer);
  });

  it('formats missing write_file path/content as a clean actionable error', () => {
    const out = formatSchemaValidationFeedback('write_file', ['path: Required', 'content: Required']);
    expect(out).toBe(WRITE_FILE_REQUIRED_INPUT_ERROR);
    expect(out).not.toContain('ZodError');
  });

  it('formats missing read_file and todo_write inputs cleanly', async () => {
    const {formatMissingRequiredToolInput} = await import('../../src/agent/toolInputRepair.js');
    expect(formatMissingRequiredToolInput('read_file', ['path: Required'])).toBe('read_file requires a path. The model omitted the file path.');
    expect(formatMissingRequiredToolInput('todo_write', ['todos: Required'])).toBe('todo_write requires a todos array. The model omitted todo items.');
  });

  it('can include write_file details in debug mode', () => {
    process.env.APEIRONCODE_DEBUG = '1';
    const out = formatWriteFileInputError(['path: Required']);
    delete process.env.APEIRONCODE_DEBUG;
    expect(out).toContain(WRITE_FILE_REQUIRED_INPUT_ERROR);
    expect(out).toContain('path: Required');
  });
});

describe('shouldRetryToolInput', () => {
  it('returns true for JSON error', () => {
    expect(shouldRetryToolInput(new Error('Invalid JSON'), 0)).toBe(true);
  });
  it('returns false after 3 attempts', () => {
    expect(shouldRetryToolInput(new Error('Invalid JSON'), 3)).toBe(false);
  });
  it('returns false for unrelated errors', () => {
    expect(shouldRetryToolInput(new Error('network failed'), 0)).toBe(false);
  });
  it('does not retry missing write_file path/content', () => {
    expect(shouldRetryToolInput(new Error(WRITE_FILE_REQUIRED_INPUT_ERROR), 0)).toBe(false);
  });
});

describe('isMissingWriteFileInput', () => {
  it('detects missing write_file path/content', () => {
    expect(isMissingWriteFileInput('write_file', {})).toBe(true);
    expect(isMissingWriteFileInput('write_file', {path: 'x'})).toBe(true);
    expect(isMissingWriteFileInput('write_file', {path: 'x', content: ''})).toBe(false);
    expect(isMissingWriteFileInput('read_file', {})).toBe(false);
  });
});
