import type {AgentMode} from '../../agent/types.js';

export interface BgTaskCreateOptions {
  kind?: string;
  worktree?: boolean;
  agent?: string;
  skill?: string[];
  command?: string;
  start?: boolean;
}

import type {
  CostCliOptions,
  ContextRefreshCliOptions,
  ConfigCommandKey,
  ConfigSetOptions,
  DoctorCliOptions,
  HistoryCliOptions,
  LspCliOptions,
  ProviderTestCliOptions,
  RevertCliOptions,
  RootCliOptions,
  SearchCliOptions,
  SessionCliOptions,
} from '../args.js';

export interface CliHandlers {
  brainAudit?: () => Promise<void>;
  brainBuildPlan?: (prompt: string) => Promise<void>;
  brainContext?: (prompt: string) => Promise<void>;
  brainInit?: (options?: {yes?: boolean; dryRun?: boolean}) => Promise<void>;
  brainMemory?: () => Promise<void>;
  brainOrchestrate?: (prompt: string) => Promise<void>;
  brainPlan?: () => Promise<void>;
  brainPreviewApply?: (id: string, options?: {yes?: boolean}) => Promise<void>;
  brainPreviewShow?: (id: string) => Promise<void>;
  brainPreviews?: () => Promise<void>;
  brainRoute?: (prompt: string) => Promise<void>;
  brainRuntime?: (prompt: string) => Promise<void>;
  brainExplain?: (prompt: string) => Promise<void>;
  brainShow?: () => Promise<void>;
  brainStatus?: () => Promise<void>;
  brainSync?: (options?: {yes?: boolean}) => Promise<void>;
  brainSyncPreview?: () => Promise<void>;
  brainTasks?: () => Promise<void>;
  brainUpdate?: (options?: {yes?: boolean; summary?: string}) => Promise<void>;
  continueTask: (taskId?: string) => Promise<void>;
  cost: (options: CostCliOptions) => Promise<void>;
  deleteSession: (sessionId: string) => Promise<void>;
  doctor: (options: DoctorCliOptions) => Promise<void>;
  debugConfig: () => Promise<void>;
  debugLogs: (options?: {last?: number}) => Promise<void>;
  debugTokens: () => Promise<void>;
  debugTraces: (options?: {last?: number}) => Promise<void>;
  getConfigValue: (key: ConfigCommandKey, options: ConfigSetOptions) => Promise<void>;
  history: (options: HistoryCliOptions) => Promise<void>;
  listSessions: (options: SessionCliOptions) => Promise<void>;
  listConfig: () => Promise<void>;
  addPermission: (rule: string) => Promise<void>;
  listPermissions: () => Promise<void>;
  checkPermission: (resource: string) => Promise<void>;
  contextFiles: (query: string) => Promise<void>;
  contextBudget: () => Promise<void>;
  contextExplain: (query: string) => Promise<void>;
  contextIndex: () => Promise<void>;
  contextMap: () => Promise<void>;
  contextRefresh: (options: ContextRefreshCliOptions) => Promise<void>;
  contextSymbols: (query: string) => Promise<void>;
  contextWhy: (query?: string) => Promise<void>;
  contextPlan?: (prompt: string) => Promise<void>;
  contextAffected?: (file: string) => Promise<void>;
  contextTests?: (file: string) => Promise<void>;
  contextView?: () => Promise<void>;
  debugCompression?: () => Promise<void>;
  agents: () => Promise<void>;
  agentShow: (name: string) => Promise<void>;
  agentRun: (name: string, task: string) => Promise<void>;
  teamPlan: (task: string, options?: {parallelReadonly?: boolean}) => Promise<void>;
  teamApply: (teamRunId: string, options?: {file?: string; force?: boolean}) => Promise<void>;
  teamArtifact: (teamRunId: string, artifactId: string, options?: {preview?: boolean}) => Promise<void>;
  teamArtifacts: (teamRunId: string, options?: {filter?: string; search?: string}) => Promise<void>;
  teamCockpit: (teamRunId: string) => Promise<void>;
  teamConflicts: (teamRunId: string, options?: {file?: string; json?: boolean}) => Promise<void>;
  teamDiscard: (teamRunId: string) => Promise<void>;
  teamExport: (teamRunId: string) => Promise<void>;
  teamExportPatch: (teamRunId: string, options?: {file?: string; includeConflicts?: boolean}) => Promise<void>;
  teamIgnored: (teamRunId: string) => Promise<void>;
  teamMergePlan: (teamRunId: string) => Promise<void>;
  teamReview: (teamRunId: string, options?: {interactive?: boolean}) => Promise<void>;
  teamResolve: (teamRunId: string, options?: {action?: string; file?: string}) => Promise<void>;
  teamRunShow: (teamRunId: string) => Promise<void>;
  teamRuns: () => Promise<void>;
  teamRun: (task: string, options?: {dryRun?: boolean; parallelReadonly?: boolean; workspace?: string}) => Promise<void>;
  teamValidatePatch: (teamRunId: string, patchPath?: string) => Promise<void>;
  teamWorkspaceCleanup: () => Promise<void>;
  teamWorkspaces: () => Promise<void>;
  githubStatus: () => Promise<void>;
  githubRepo: () => Promise<void>;
  githubIssues: () => Promise<void>;
  githubIssue: (number: string) => Promise<void>;
  githubIssueComment: (number: string, text: string, options?: {dryRun?: boolean}) => Promise<void>;
  githubIssueCreate: (options: {body?: string; dryRun?: boolean; title?: string}) => Promise<void>;
  githubPrs: () => Promise<void>;
  githubPr: (number: string) => Promise<void>;
  githubPrComment: (number: string, text: string, options?: {dryRun?: boolean}) => Promise<void>;
  githubPrCreate: (options: {base?: string; body?: string; dryRun?: boolean; head?: string; title?: string}) => Promise<void>;
  githubPrReview: (number: string, options?: {dryRun?: boolean; post?: boolean}) => Promise<void>;
  githubPrSummary: (number: string) => Promise<void>;
  githubActions: (runId?: string) => Promise<void>;
  githubCiExplain: (runId?: string) => Promise<void>;
  githubActionSimulate?: (eventJson: string) => Promise<void>;
  githubAutomateFixCi?: (target: string, options?: {dryRun?: boolean}) => Promise<void>;
  githubAutomateIssue?: (target: string, options?: {dryRun?: boolean}) => Promise<void>;
  githubAutomatePrReview?: (target: string, options?: {dryRun?: boolean}) => Promise<void>;
  githubParseCommand?: (comment: string) => Promise<void>;
  securityStatus: () => Promise<void>;
  sandboxDoctor: () => Promise<void>;
  sandboxStatus: () => Promise<void>;
  setup: (options?: {local?: boolean; provider?: string}) => Promise<void>;
  setupReset: (options?: {dryRun?: boolean}) => Promise<void>;
  setupStatus: () => Promise<void>;
  hooks: () => Promise<void>;
  hookList: () => Promise<void>;
  hookShow: (name: string) => Promise<void>;
  hookTest: (name: string) => Promise<void>;
  hookEnable: (name: string) => Promise<void>;
  hookDisable: (name: string) => Promise<void>;
  hookEvents: () => Promise<void>;
  repoMap: () => Promise<void>;
  repoSummary: () => Promise<void>;
  repoSymbols: (query: string) => Promise<void>;
  listPlugins: () => Promise<void>;
  listMcp: () => Promise<void>;
  listMcpTools: (serverName: string, options?: {all?: boolean}) => Promise<void>;
  mcpAddHttp?: (id: string, options: {url: string}) => Promise<void>;
  mcpAddSse?: (id: string, options: {url: string}) => Promise<void>;
  mcpAddStdio?: (id: string, options: {args?: string[]; command: string}) => Promise<void>;
  mcpCall?: (serverName: string, toolName: string, options: {json?: string}) => Promise<void>;
  mcpDisable?: (serverName: string) => Promise<void>;
  mcpAuthLogin?: (serverName: string) => Promise<void>;
  mcpAuthLogout?: (serverName: string) => Promise<void>;
  mcpAuthStatus?: (serverName: string) => Promise<void>;
  mcpAllow?: (serverName: string, toolName: string) => Promise<void>;
  mcpDeny?: (serverName: string, toolName: string) => Promise<void>;
  mcpEnable?: (serverName: string) => Promise<void>;
  mcpPermissions?: (serverName: string) => Promise<void>;
  mcpPrompt?: (serverName: string, promptName: string, options?: {preview?: boolean}) => Promise<void>;
  mcpPrompts?: (serverName: string) => Promise<void>;
  mcpRead?: (serverName: string, uri: string, options?: {addToContext?: boolean}) => Promise<void>;
  mcpRemove?: (serverName: string) => Promise<void>;
  mcpResources?: (serverName: string) => Promise<void>;
  mcpSearch?: (query: string) => Promise<void>;
  listTools: () => Promise<void>;
  memoryShow: (options: {global?: boolean}) => Promise<void>;
  memorySummarize: (options: {global?: boolean}) => Promise<void>;
  memoryEdit: (options: {global?: boolean}) => Promise<void>;
  memoryClear: (options: {global?: boolean}) => Promise<void>;
  memorySearch: (query: string, options: SearchCliOptions) => Promise<void>;
  memoryGraph: () => Promise<void>;
  memoryRelated: (query: string) => Promise<void>;
  memoryReview: (options?: {confidence?: string; source?: string; status?: string; team?: string}) => Promise<void>;
  memoryPrune: () => Promise<void>;
  memoryLearn: (fact: string) => Promise<void>;
  memorySuggestionApprove: (id?: string, options?: {all?: boolean}) => Promise<void>;
  memorySuggestionReject: (id?: string, options?: {all?: boolean}) => Promise<void>;
  memorySuggestionShow: (id: string) => Promise<void>;
  memorySuggestions: () => Promise<void>;
  memoryConflicts: () => Promise<void>;
  memoryForgetSession: (sessionId: string, options?: {yes?: boolean}) => Promise<void>;
  memoryRollback: (id: string, options?: {yes?: boolean}) => Promise<void>;
  memorySource: (id: string) => Promise<void>;
  memoryStale: () => Promise<void>;
  memoryWhy: (query?: string) => Promise<void>;
  memoryExplain?: (query: string) => Promise<void>;
  memoryVerify?: () => Promise<void>;
  memoryCompact?: () => Promise<void>;
  memoryExport?: (options?: {redacted?: boolean}) => Promise<void>;
  memoryForget?: (id: string, options?: {yes?: boolean}) => Promise<void>;
  runtimeStatus?: () => Promise<void>;
  runtimeCheckpoints?: () => Promise<void>;
  runtimeRollback?: (checkpointId: string, options?: {yes?: boolean}) => Promise<void>;
  runtimeSummary?: (sessionId?: string) => Promise<void>;
  skills: () => Promise<void>;
  skillBrowser: (options?: {filter?: string; search?: string}) => Promise<void>;
  skillDisable: (name: string) => Promise<void>;
  skillEnable: (name: string) => Promise<void>;
  skillList: () => Promise<void>;
  skillTemplates: () => Promise<void>;
  skillTrust: (name: string) => Promise<void>;
  skillShow: (name: string) => Promise<void>;
  skillRun: (name: string, options?: {input?: string; noRun?: boolean}) => Promise<void>;
  skillCreate: (name: string) => Promise<void>;
  skillGenerate: (description: string) => Promise<void>;
  skillValidate: (name: string) => Promise<void>;
  skillDelete: (name: string) => Promise<void>;
  skillExport: (name: string) => Promise<void>;
  skillImport: (filePath: string) => Promise<void>;
  modelList: (role?: string) => Promise<void>;
  modelRecommend: (role?: string) => Promise<void>;
  ollamaModels: () => Promise<void>;
  ollamaPullHint: (model: string) => Promise<void>;
  ollamaRecommend: () => Promise<void>;
  ollamaStatus: () => Promise<void>;
  providerDoctor: (options: ProviderTestCliOptions) => Promise<void>;
  providerEnv: (providerName?: string) => Promise<void>;
  providerFallback: (role?: string) => Promise<void>;
  providerFallbackSimulate: (kind: string, role?: string) => Promise<void>;
  providerFallbackSet: (role: string, chain: string) => Promise<void>;
  providerFallbackTest: (role?: string) => Promise<void>;
  providerList: () => Promise<void>;
  providerSetup: (providerName?: string) => Promise<void>;
  providerTest: (options: ProviderTestCliOptions) => Promise<void>;
  testMcp: (serverName: string) => Promise<void>;
  planApprove: (planId: string) => Promise<void>;
  planClear: () => Promise<void>;
  planCreate: (goal: string) => Promise<void>;
  planDelete: (taskId: string) => Promise<void>;
  planExecute: (planId: string) => Promise<void>;
  planList: () => Promise<void>;
  planPause: (taskId: string) => Promise<void>;
  planResume: (taskId: string) => Promise<void>;
  planRevise: (planId: string, instructions: string) => Promise<void>;
  planShow: (taskId?: string) => Promise<void>;
  planStatus: (taskId?: string) => Promise<void>;
  removePermission: (rule: string) => Promise<void>;
  revert: (target?: string, options?: RevertCliOptions) => Promise<void>;
  resumeSession: (sessionId: string) => Promise<void>;
  runRoot: (prompt: string | undefined, options: RootCliOptions) => Promise<void>;
  search: (query: string, options: SearchCliOptions) => Promise<void>;
  setConfigValue: (
    key: ConfigCommandKey,
    value: string,
    options: ConfigSetOptions,
  ) => Promise<void>;
  webFetch: (url: string) => Promise<void>;
  webResearch: (query: string) => Promise<void>;
  webSearch: (query: string) => Promise<void>;
  workflowList: () => Promise<void>;
  workflowReport: (runId: string) => Promise<void>;
  workflowRun: (name: string, options?: {dryRun?: boolean; task?: string}) => Promise<void>;
  workflowShow: (name: string) => Promise<void>;
  markdownAgentList?: () => Promise<void>;
  markdownAgentShow?: (name: string) => Promise<void>;
  markdownSkillList?: () => Promise<void>;
  markdownSkillShow?: (name: string) => Promise<void>;
  markdownCommandList?: () => Promise<void>;
  markdownCommandShow?: (name: string) => Promise<void>;
  markdownCommandRun?: (name: string, args: string) => Promise<void>;
  // Phase 16D: Background task commands
  bgTaskCreate?: (prompt: string, options?: BgTaskCreateOptions) => Promise<void>;
  bgTaskList?: (options?: {status?: string; kind?: string}) => Promise<void>;
  bgTaskShow?: (taskId: string) => Promise<void>;
  bgTaskOutput?: (taskId: string) => Promise<void>;
  bgTaskStop?: (taskId: string) => Promise<void>;
  bgTaskResume?: (taskId: string) => Promise<void>;
  // Phase 16D: Worktree commands
  worktreeList?: () => Promise<void>;
  worktreeShow?: (id: string) => Promise<void>;
  worktreeRemove?: (id: string, options?: {yes?: boolean}) => Promise<void>;
  connectorEnv: (connector: string) => Promise<void>;
  connectorList: () => Promise<void>;
  evalList: () => Promise<void>;
  evalReport: (suite?: string) => Promise<void>;
  evalRun: (name: string | undefined, options?: {all?: boolean}) => Promise<void>;
  lspStatus: (options: LspCliOptions) => Promise<void>;
  lspSessions: (options: LspCliOptions) => Promise<void>;
  lspRestart: (options: LspCliOptions) => Promise<void>;
  lspStop: (options: LspCliOptions) => Promise<void>;
  lspCache: () => Promise<void>;
  lspCacheClear: () => Promise<void>;
  lspDiagnostics: (file: string | undefined, options: LspCliOptions) => Promise<void>;
  lspDefinition: (file: string | undefined, line: string | undefined, character: string | undefined, options: LspCliOptions) => Promise<void>;
  lspReferences: (file: string | undefined, line: string | undefined, character: string | undefined, options: LspCliOptions) => Promise<void>;
  lspSymbols: (file: string, options: LspCliOptions) => Promise<void>;
  sessions: (options?: {all?: boolean}) => Promise<void>;
  sessionList: (options?: {all?: boolean}) => Promise<void>;
  sessionStart: (goal: string, options?: {mode?: AgentMode; provider?: string; model?: string; background?: boolean; run?: boolean}) => Promise<void>;
  sessionShow: (sessionId: string) => Promise<void>;
  sessionAttach: (sessionId: string) => Promise<void>;
  sessionLogs: (sessionId: string, options?: {tail?: number; follow?: boolean}) => Promise<void>;
  sessionPause: (sessionId: string) => Promise<void>;
  sessionResume: (sessionId: string) => Promise<void>;
  sessionRunWorker: (sessionId: string) => Promise<void>;
  sessionStop: (sessionId: string) => Promise<void>;
  sessionDelete: (sessionId: string) => Promise<void>;
  sessionExport: (sessionId: string, options?: {format?: 'html' | 'json' | 'markdown'; output?: string}) => Promise<void>;
  sessionLocks: () => Promise<void>;
  sessionUnlock: (file: string, options?: {all?: boolean}) => Promise<void>;
  share: (sessionIdOrLatest: string, options?: {format?: 'json' | 'markdown' | 'html'}) => Promise<void>;
  // Phase 16E: Bridge CLI
  bridgeStart?: (options?: {port?: number}) => Promise<void>;
  bridgeStatus?: () => Promise<void>;
  bridgeToken?: (options?: {show?: boolean}) => Promise<void>;
  bridgeStop?: () => Promise<void>;
}
