import type {AutomationResult, AutomationStep} from './types.js';

const formatStep = (step: AutomationStep): string =>
  `- [${step.status}] ${step.name}${step.detail ? `: ${step.detail}` : ''}`;

export const buildAutomationSummary = (result: AutomationResult): string => {
  const lines = [
    `ApeironCode automation: ${result.workflow}`,
    `Status: ${result.status}${result.dryRun ? ' (dry-run)' : ''}`,
    '',
    'Steps:',
    ...result.steps.map(formatStep),
  ];
  if (result.branchName) {
    lines.push('', `Branch: ${result.branchName}`);
  }
  if (result.commitSha) {
    lines.push(`Commit: ${result.commitSha.slice(0, 12)}`);
  }
  if (result.prNumber !== undefined) {
    lines.push(`PR #${result.prNumber}${result.prUrl ? ` — ${result.prUrl}` : ''}`);
  }
  if (result.message) {
    lines.push('', result.message);
  }
  return lines.join('\n');
};

export const buildCommentBody = (result: AutomationResult): string => {
  const status = result.status === 'succeeded' ? 'completed successfully' : `did not complete (status: ${result.status})`;
  return [
    `ApeironCode ${result.workflow} ${status}${result.dryRun ? ' in dry-run mode' : ''}.`,
    '',
    buildAutomationSummary(result),
    '',
    '_This comment was generated by ApeironCode automation._',
  ].join('\n');
};
